services:
  - type: web
    name: whatsx-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: whatsx-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_SENDER
        sync: false
      - key: CLIENT_ORIGIN
        sync: false

databases:
  - name: whatsx-db
    plan: free
